### ISSUE TITLE
Having two documents open at the same time?

### ISSUE THREAD

**Issue by shervinafshar** [benweet/stackedit#10]
I'm using Stackedit with Google Drive. Currently, it's not possible to have two different files open. Is this a bug or a feature?

**Comment by theoryshaw** [comment]
1+

**Comment by denjello** [comment]
Would extending the localstorage file array by registering the **active** file in localstorage with the active windowId be a possible solution in order to create a sort of window/tab lock (when not synchronizing to google drive / whatever)? 

file.%ID%.windowId = utils.id();

and then using the logic in the checkWindowUnique function at `public/res/core.js` to check if the same file is already open somewhere else?

**Comment by victorel-petrovich** [comment]
+1

**Comment by NealBozeman** [comment]
+1

**Comment by mythos1717** [comment]
I'd like to put my vote in for this feature as well. I understand the complexity of having to keep track/sync the same file across multiple instances. However, I have another use for it. I'd like to be able to open multiple documents to combine parts and/or review to see if they could be combined. As it stands right now, that can only be done, by opening one, reading it, closing it and opening another. This isn't a big need for me, but occasionally I find a use for it.

I've been thinking about how this could be done. I'm assuming that (at least with Google Drive) you're reading the unique id of each file. If you were to check, when a person tried to open another document that it didn't match a current open instance with the same id, you could allow people to open different files from Drive at the same time. Just a thought. 

For now, I can use another program, but I'd love to see if this could be implemented in the future.

**Comment by VillageHubertChen** [comment]
+1 I am typically writing on several different documents the same time. I agree with previous post. Do not allow to open the same document a second time, but why not allow to open a different document in a different browser window?

**Comment by SpaceFlyer** [comment]
+1

**Comment by VillageHubertChen** [comment]
For those looking for a solution to this problem: https://app.classeur.io/#!/ It works like stackedit and it allows several editor instances to be open the same time. I am using it since a while now and it is reliable.

**Comment by voddan** [comment]
@benweet this restriction is a total **show-stopper**! My workflow includes multiple files opened in different windows/screens. I write in one or two consulting the others. 

I _really really_ need a toggle/workaround to lift this restriction! Btw, I don't really care if I screw it up and edit one document from two windows! That's my mistake, not yours. The app can show me a warning, but preventing a whole bunch of use cases because of that is irresponsible.

The easiest solution from the programming point of view would be to block edition in the all but the first copy of the same document. Maybe show a warning. I did not studied your code, but it looks like a local change. This is a **major show-stopper**! 

When can we expect a resolution of this problem, namely opening several different documents in several/tabs/windows/screens?

**Comment by VillageHubertChen** [comment]
@voddan 

Your solution is to look at: http://classeur.io/ . It is the successor of stack edit. You can open the app also directly:  https://app.classeur.io/#!/  I am using Classeur with exactly the same workflow as you describe. I frequently have more than 10 Classeur windows open. You can open more than one instance of the same file.

Classeur has also many new additional features. I am currently writing on a manual to make the easier accessible. 

Stack Edit is no longer developed. Classeur is. Classeur is the improved version of Stack Edit. Just imagine the author implemented all your request and by the way renamed the app.

Let me know if you have any more questions,

Hubert

**Comment by voddan** [comment]
Thank you for the suggestion, @VillageHubertChen 

It seems that `classeur` does **not** allow me to open an arbitrary `.md` file from my Google Disk, so I can't use it for my existing files. 

Stackedit is still unique, I just hope that this misunderstanding will be resolved soon enough.

**Comment by VillageHubertChen** [comment]
@voddan 

Thanks for your reply. Your post did not mentioned Google Drive, but I see now that the first post did. My apologies for any misunderstanding! Now lets move on to try to solve your problem.

It may be possible that I have a solution for you and then maybe not. We are a decent sized team of collaborative writers. We used google drive / google docs previously for our collaborative writing.

If you would describe me your workflow and your targets I may be able to come up with an acceptable solution for you.

**Comment by benweet** [comment]
The v5 now supports multiple tabs.
