### ISSUE TITLE
Add doctoc support

### ISSUE THREAD

**Issue by ammario** [benweet/stackedit#1044]
[DocToc](https://github.com/thlorenz/doctoc) support would be a super useful feature

**Comment by simonmysun** [comment]
What's the difference between using DocToc and using `[TOC]` in stackedit?

**Comment by ammario** [comment]
`[TOC]`  is only understood by stackedit.

**Comment by simonmysun** [comment]
I see. 

Stackedit render Markdown to HTML, while DocToc changes the original input. I don't think automatically generating TOC is good. When you break the generated code occasionally, there will be duplicated TOC and it is difficult to resture. When do you think is the proper time to generate this DocToc style TOC?

**Comment by ammario** [comment]
I think there should be a TOC/DOCTOC button in the toolbar.

**Comment by Zearin** [comment]
If you want the RESULT of using `[TOC]`, just do the following:

1. **Add `[TOC]`**, so that StackEdit generates the Table of Contents.
1. **Copy the HTML of the generated TOC**.
1. **Use StackEdit’s _Convert HTML ▶︎ Markdown_ feature**, overwrite the original `[TOC]` from _Step 1_ with the conversion result.

(Not as easy as what you want, I realize—just a workaround, if you really hate using `[TOC]`.  Perhaps somone could write a StackEdit extension to automate these steps…)

**Comment by kgashok** [comment]
The HTML code generated is kind of crappy...

**Comment by benweet** [comment]
Support for `[toc]` has been dropped in the v5 (https://stackedit.io/app). Please use handlebars templates and helpers to make exotic tocs in your exports.
