### ISSUE TITLE
Is stackedit is being maintained?

### ISSUE THREAD

**Issue by eldade** [benweet/stackedit#1071]
Last commit was about a year ago -- perhaps there is a fork that's actively maintained?

**Comment by bradley-fastorientation** [comment]
It seems like the author is actively developing [Classeur](https://app.classeur.io/#!/). A quick Google search for [the difference between the two](https://classeur.zendesk.com/hc/en-us/articles/208540035-What-is-the-difference-between-StackEdit-and-Classeur-) revealed this:

> StackEdit is no longer being developed. Thus, Classeur is the true successor of StackEdit.

**Comment by Redsandro** [comment]
That's sad. I like StackEdit. Could use bugfixes. I hope forces will co-operate to bring about a change of ownership to someone with more love for the project.

**Comment by dtu-compute** [comment]
If you are looking for working https and credentials for stackedit to couchdb, then take a look at the fork https://github.com/dtu-compute/dtu-enote-stackedit . The fork is not intended for general purpose, as it have other changes, but the couchdb fixes are.

**Comment by rschulman** [comment]
@dtu-compute If someone forks stack-edit to restart development, would you be willing to participate in that and upstream some of the improvements you've made? I'm curious about seeing if it can be made to be a wholly client-side app backed by couchdb.

**Comment by dtu-compute** [comment]
Probably not. If someone forked it and wanted to maintain StackEdit, then it would be easy to merge in our fixes.

After having used StackEdit in production for 6 months, it is not really suitable to mass document editing for our needs. It is a webapp (client side app), and no small amount of fixing can change that.

So we will most likely build our own in the next month, but with file based backend instead of couchdb and no menus. This will not be a general purpose editor, but if someone would be willing to send pull requests to make it general purpose, then we would certainly merge them in.

**Comment by Bilge** [comment]
Unfortunately @benweet has become terminally disillusioned with the belief that StackEdit's double-pane view can be condensed into a single pane view as in Classeur. However it is trivial to prove how broken this model is. Classeur cannot:

* Render HTML markup. It cannot display `<img>` elements nor apply custom alignment.
* Render HTML entities.
* Render links nor follow inter-document links.
* Display heading sizes in monospace mode nor align heading underlines in variable-width mode.

All of these things are already possible in StackEdit with the two-paned approach. This is irrelevant, however, since @benweet died towards the end of 2016. RIP ☠️

**Comment by Redsandro** [comment]
@Bilge said:
> @benweet died towards the end of 2016. RIP :skull_and_crossbones:

That's terrible to hear! :fearful: Although I don't know you; not sure if joking or sinsere.

**Comment by eldade** [comment]
@Bilge I do see that he's become completely inactive online sometime late 2016. What makes you think he's dead?!

**Comment by benweet** [comment]
Closing the issue, as it's neither a change request nor a bug.

**Comment by Bilge** [comment]
@benweet Cool, dude. Why don't you just ignore all the issues raised herein.

**Comment by Redsandro** [comment]
Aww, not funny. I've seen projects abandoned due to accidents twice.

@benweet I'm glad you're alive. You've invested a lot of time in this project and you don't owe anyone your free time.

**Comment by philip-ulrich** [comment]
It's sad that this is seemingly the only issue @benweet has even touched in a very long time. Yet he is still willing to take peoples money. Sadly I contributed financially to this and because of an issue that is not being addressed, I cannot use this.

**Comment by cryptogee** [comment]
I can't even believe it, this guy is a fucking asshole! Takes peoples money and then leaves us high and dry!! Fucking Wanker!!!

**Comment by adrien-be** [comment]
**StackEdit** just launched a **beta version of the 5th version**

So I doubt the product is being left aside

**Comment by jkyeung** [comment]
Not only is StackEdit still alive, Classeur seems to be going away at the end of May this year.

**Comment by dayfuaim** [comment]
But I dare asking: %SUBJ
~3 years since last commits.

How's it going with project?

**Comment by andrisi** [comment]
https://ui.toast.com/tui-editor is a good and well maintained alternative

**Comment by cryptogee** [comment]
Lol, I found a good alternative 4 years ago. It's online it's called Draft,
better than that piece of poo stackedit.

**Comment by Friggler** [comment]
this one?
https://getdrafts.com

**Comment by Redsandro** [comment]
My last comment was more than 5 years ago. Meanwhile I have moved to [Zettlr](https://www.zettlr.com/). It is an app in stead of a website, but it works on actual text files in stead of some database like Joplin. So your project folders can be editor-agnostic collabs (e.g. markdown based documentation project on github), and you can open multiple project folders at the same time.

I have one such folder shared with Nextcloud. So I can edit those notes in the browser on Nextcloud editor as well as well as with [Nextcloud Notes](https://f-droid.org/en/packages/it.niedermann.owncloud.notes/) on my smartphone. Not as advanced as Zettlr itself or as nice as Stackedit, but still a good way to get notes on your phone.

**Comment by knackstedt** [comment]
I've begun working on an Angular fork of StackEdit, trying to simplify the very interconnected Vue code (incl. various other changes).
As of right now, I'm working on publishing it on npmjs as a standalone web component. I'll also look into making a projector interface for it (like trilium, zettlr and/or obsidian), but that's not a big driver for me so I don't have much motivation :)

In my case, I really wanted to use it as an in-app markdown editor for a few things. Gotta love those permissive licenses :D


https://github.com/knackstedt/stackedit/tree/master
