### ISSUE TITLE
Where are the settings in v5?

### ISSUE THREAD

**Issue by Daniel-Hug** [benweet/stackedit#1125]
I want to enable the `[TOC]` (Table Of Contents) feature. I don't see anything for this in menu>more>settings. I find it odd that this is disabled by default especially considering that it is used in the welcome document.

I'm also missing the extensions I had in v4. How do I do those in 5?

**Comment by benweet** [comment]
`[TOC]` markers are not supported anymore. But you have the possibility for your exports to generate table of contents via templates (see the template named `Styled HTML with TOC`). Pandoc generates one as well.

**Comment by dcy** [comment]
Sorry to hear that, [TOC] is a good feature.

**Comment by dcy** [comment]
@benweet Could you tell me how to use `Styled HTML with TOC`?

**Comment by nerdmed** [comment]
@benweet sad to see that the TOC feature is being removed. I have just started using this as a developer in our team and it was the first thing that we needed when we created some documentation with stackedit - is there a plan to add it back? I can see that it is implemented via the menu? Is the community interested to get some support to add this back in version 5?

**Comment by Nir-Bhay** [comment]
The balance between a clean editor and accessible settings is definitely a challenge. In [Markups](https://github.com/Nir-Bhay/markups), we took a "UI-first" approach to solve this. 

We’ve implemented a simplified, intuitive Settings UI alongside a built-in Table of Contents (TOC) and navigation sidebar. Instead of burying these features, they are part of a responsive workspace that lets you toggle navigation and formatting tools without losing focus on your text. Feel free to check out the new layout here: https://github.com/Nir-Bhay/markups
