### ISSUE TITLE
So.Slow.

### ISSUE THREAD

**Issue by alankis** [benweet/stackedit#1171]
I am absolutely amazed by stack edit and I am using it for writing the CV, which forced me to become a sponsor just to realize that StackEdit became extremely slow. So slow that is completely unusable, but I like the export to PDF option. Tested on latest Fedora 27 and Google Chrome/Firefox browser latest stable version. Both in incognito and normal mode without any loaded extension. Is there any workaround for this issue?

**Comment by benweet** [comment]
Hi,
Can you share a markdown file to reproduce the issue ?
Thanks

**Comment by sradevski** [comment]
For me the culprit was Grammarly on Google Chrome. After trying to run in incognito it got a bit faster, but it is still a bit laggy. I did a quick performance snapshot and it seems that the main performance hit is keypress event handler + update layer tree. Cool tool btw! :)

**Comment by MichielDP** [comment]
Been having the same issue. We have a team which works from a google drive folder where we all have linked with the StackEdit app. When we open files from their it very commoj that it either takes super long to load, doesn't load at all or loads the wrong file. Really demotivating because this tool looked so promising!

**Comment by benweet** [comment]
Google Drive file loading should be faster now with v5. Please reopen a new ticket for any other performance issue with a way to reproduce it.
