### ISSUE TITLE
Support Exporting/Importing/Syncing to/from Google TEAM Drives

### ISSUE THREAD

**Issue by KOGI** [benweet/stackedit#1187]
The Google Drive integration is excellent, but it appears I cannot use the feature with my company's team drive, which means I can't (easily) share my docs with other colleagues or keep them in the company library with the rest of our documents.

**Comment by jondkinney** [comment]
I'm confused by the collaboration feature. What's the difference between supporting google drive tied to a company's GSuite account or not? Trying to open a workspace between two people in our company's google account/drive isn't working. A guide on how to setup workspaces and collaboration would be great because creating a workspace in a shared drive folder and opening it as another user isn't working.

**Comment by stephenprater** [comment]
https://github.com/benweet/stackedit/pull/1285

**Comment by benweet** [comment]
Fixed in v5.11.1.
