### ISSUE TITLE
How To Insert an Image From a Local File?

### ISSUE THREAD

**Issue by nobozo** [benweet/stackedit#121]
I just found Stackedit. Very nice!!

I do have one question. I tried to insert an image, and a window opened asking for the URL of the image. Is it possible to insert an image stored on my local file system (perhaps using the file:/// syntax) or in my browser local storage? Also, are all image types displayable by the browser acceptable to Stackedit?

Thanks for the great work!
Jon Forrest

**Comment by jezzsantos** [comment]
@benweet understood about the storage concern, but the issue is not one of storage, this is a usability issue.

The issue can be restated as such "can I use images that I already have locally, without additional (rote) steps to get them where they can be used?"

You should acknowledge that people have their images wherever they have their images, and telling them where they should have them is not going to help them.

Great that you can drag and drop them and do the heavy lifting by uploading to a google drive. Exactly the right answer!

**Comment by fopitz** [comment]
Drag and drop does not work for me. Can somebody help me?

**Comment by kukrishna** [comment]
I think that we should have an option to add images stored on local drive. It is especially necessary if you are offline or have a slow connection, like I have right now.  

I figured out a way to do it if you have apache installed. 

I have all my files and images kept in `~/mysite/kukrishna.github.io` 
My username is `kkrishna`

First, you need to enable the apache userdir module.
`sudo a2enmod userdir`
Next you need to edit the file `/etc/apache2/mods-enabled/userdir.conf` to set the base directory variable. Edit the second line so that it looks like this
`       UserDir mysite/kukrishna.github.io`
Now restart apache
`sudo service apache2 restart`
And it's done.

You can access `~/mysite/kukrishna.github.io/PATH/FILE` by using the URL `localhost/~kkrishna/PATH/FILE`.

This URL would also work in StackEdit. 

I learnt this thing from the top answer   [here](http://askubuntu.com/questions/14301/apache-symlinked-to-home-directory-permission-errors)
