### ISSUE TITLE
Typing Chinese character doesn't work

### ISSUE THREAD

**Issue by wuqingze** [benweet/stackedit#1215]
when i type the Japanese character (or Chinese character) on the left editor page, the character doesn't show on the right preview page.
![image](https://user-images.githubusercontent.com/32740722/35518261-0260b89a-054c-11e8-94de-980c6a272a75.png)

**Comment by wuqingze** [comment]
@Daltan your solution isn't good because typing space disobeys the people  typing habit.

**Comment by atsushieno** [comment]
It indeed is a problem because there is no use of half-width spaces in our syntax (either in Japanese or Chinese). This never happened on classeur.io (I just migrated from there).

Possible solutions I can quickly think of:
- very compromised: U+3001 (、), U+3002 (。)、U+FF0C (，) and U+FF0D (．) to trigger preview updates.
- somewhat compromised: characters above + CJK ideographs in BMP (4E00–9FFF) + Hiragana (U+3040-U+309F) + Katakana (U+30A0-U+30FF) to trigger preview updates.
- logical: check unicode character type and determine whether to trigger preview updates or not.

**Comment by benweet** [comment]
Is it better with v5.8?

**Comment by atsushieno** [comment]
Yes! It just works as I expect (not sure for Chinese). Thanks :-)

**Comment by wuqingze** [comment]
yes! it works, Chinese ok!
