### ISSUE TITLE
No more \newcommand in StackEdit 5

### ISSUE THREAD

**Issue by petered** [benweet/stackedit#1216]
In StackEdit 4 I just began each of my documents with a preamble that contained a bunch of custom commands.  e.g. 

```
$$
\newcommand{\pderiv}[2]{\frac{\partial #1}{\partial #2}}
\newcommand{\argmax}[1]{\underset{#1}{\operatorname{argmax}}}
\newcommand{\argmin}[1]{\underset{#1}{\operatorname{argmin}}}
\newcommand{\switch}[3]{\begin{cases} #2 & \text{if } {#1} \\ #3 &\text{otherwise}\end{cases}}
$$
```

I see that using \newcommand is no longer allowed in StackEdit 5 (guess because Katex is now used instead of MathJax?).

This is kind of a deal-breaker for me.  Is there any workaround other than reverting to StackEdit 4?  Maybe there's a way to make it use MathJax?

**Comment by benweet** [comment]
Yes the v5 uses katex. We have to wait for this ticket to be closed: https://github.com/Khan/KaTeX/issues/37

**Comment by RoyiAvital** [comment]
KaTeX is really behind MathJaX.
It hurts Students using StackEdit.

Any chance you give us the option to use MathJaX as it used to be?

Thank You.

**Comment by petered** [comment]
@RoyiAvital you can use the link https://stackedit.io/editor# to run StackEdit 4, which will allow `\newcommand`

**Comment by RoyiAvital** [comment]
@petered , Well then other features are missing (Dropbox).
I don't get the idea of reducing features between versions.
StackEdit was perfect because of its perfect Math support and that was the feature I paid for.
Breaking compatibility doesn't make sense in my opinion, I need to find other solution.

So far Visual Studio Code + Markdown Preview Enhanced extension are the closest I can get to StackEdit as it was.

**Comment by Menci** [comment]
I'm working on my project Moeditor, a local markdown editor app. Maybe I'll use StackEdit 5's core and add MathJax support.

**Comment by farleyknight** [comment]
Note that `\newcommand` has been implemented in the latest KaTeX: https://github.com/Khan/KaTeX/pull/1382

**Comment by qx211** [comment]
\newcommand still not working on stackedit5?

**Comment by petered** [comment]
Seems not yet, I still get: 

```
KaTeX parse error: Expected 'EOF', got '\newcommand' at position 1: \̲n̲e̲w̲c̲o̲m̲m̲a̲n̲d̲{\pderiv}[2]{\f…
```

**Comment by benweet** [comment]
Upgraded to katex v0.10.0-rc.1.

**Comment by qx211** [comment]
Thanks, now \newcommand works within one "$$" but still not globally...

**Comment by RoyiAvital** [comment]
I still find this to be an issue:

![image](https://user-images.githubusercontent.com/7347975/45819922-3d363080-bcee-11e8-9aa8-0c78575176ad.png)

StackEdit used to have perfect compatibility with StackExchange network for Math.
Yet since the move to KaTeX in StackEdit 5.x this doesn't hold anymore.

I really wish for a MathJaX mode with proper scientific writing as we had before in StackEdit.
MathJaX can work with ID / Labels just like KaTeX.

**Comment by alexhkurz** [comment]
I have been using hackmd for a while but they dont support working offline, so now I am trying stackedit. But without having \newcommand available, I will not take it up more seriously. Any other recommendations? Is there a system that supports offline work and \newcommand/full mathjax?

**Comment by RoyiAvital** [comment]
@alexhkurz , I use VS Code + [MarkDown Preview Enhanced](https://github.com/shd101wyy/markdown-preview-enhanced).
It works perfectly!

If you can skip the live preview, I think the best is Sublime Text + [MarkDown Preview](https://github.com/facelessuser/MarkdownPreview) (By @facelessuser).

**Comment by JeJayPoppa** [comment]
Oh well chump idgafa so I hope you got aids gov and herpes.
N die lol fuck off i got no times for sk fks or Sharing tooth brushes
I buy homework to do and can to collect as part of myself bum duty
So voila eat a fully flavored nail and wash if down with a cord
O Lord bored deceptively i still scored.
