### ISSUE TITLE
[TOC] in the document no longer works

### ISSUE THREAD

**Issue by jordi-vaquero** [benweet/stackedit#1248]
as the title says the [TOC] in the document no longer works and only displays `[TOC]` in the visualization and exporting to pdf .

**Comment by SchoolGuy** [comment]
The reason for that is, that in stackedit 5 the `[TOC]` is depreached. There are indeed solutions out there for gaining this feature back, but insteed of trying those I recommend you to just use the "Table of Conents" Function in right side menu. If you would like to use `[TOC]` just mention me and I will try to have a look for you, so you can close the issue afterwards...

**Comment by benweet** [comment]
Indeed there are always ways to convert `[TOC]` markers in your exports via custom templates :
https://community.stackedit.io/t/replace-toc-markers-with-tables-of-contents-in-your-exports/33

**Comment by mindstretch23** [comment]
@SchoolGuy Just tried to use the TOC feature on PDF export. Is that expected to work? Would be really useful...But I dont see any TOC in the exported PDF = /

**Comment by SchoolGuy** [comment]
@mindstretch23 I never sponsored stackedit, so I am not able to test the export feature with PDF. My current knowledge on this topic is that it should work if you are using the option "Styled html with TOC" in the PDF-Export process. If you think you found a bug, then I suggest you mention @benweet and describe your problem a bit more in detail so that he can identify the bug. If you are seeking for help in using stackedit I would recommend you opening a thread or searching for an existing one on https://community.stackedit.io/
