### ISSUE TITLE
File deletion doesn't work for google drive workspace 

### ISSUE THREAD

**Issue by ArGxento** [benweet/stackedit#1260]
File deletion doesn't applied to the directory specified for the workspace in google drive and deleted files are restored after a while

**Comment by benweet** [comment]
Should be fixed in v5.11.1. However it won't work if your workspace was opened with a previous version. In that case you will have to:

Move your file, force sync and move your file again, or
Remove the Google Drive workspace from another workspace (using the "manage workspaces" menu) and reopen it, or
Reset the app and reopen the workspace.

**Comment by ArGxento** [comment]
I confirmed the problem is fixed in my environment. Thank you very much!
