### ISSUE TITLE
Constantly asking for Google authorization

### ISSUE THREAD

**Issue by vpoblete** [benweet/stackedit#1334]
The popup displaying the message *You are about to navigate to the **Google** authorization page.* keeps showing after a time even after clicking *Ok, go on* button.

![image](https://user-images.githubusercontent.com/2203544/41712192-3d6375e0-754a-11e8-8b92-937828c0437b.png)

**Comment by whiskybar** [comment]
It won't go away even after you pay (but I paid from the start anyway, the project is beautiful).

**Comment by BlueSkyLT** [comment]
I have the same problem....

**Comment by thasmo** [comment]
Same here, seems to be an issue since Jun 21, 2018 or longer.

**Comment by erhhung** [comment]
I ran into this issue for the first time **on a new computer**, and what worked for me in Chrome was that I had **Ghostery** installed and it was blocking the **Google "tracker"** that attempted to access `apis.google.com` and `accounts.google.com`.

Since I had authorized saving my docs in Google Drive, I figured that the access was legit, and I just whitelisted the "tracker" or just trust the entire site in Ghostery.

**Comment by vpoblete** [comment]
> I ran into this issue for the first time **on a new computer**, and what worked for me in Chrome was that I had **Ghostery** installed and it was blocking the **Google "tracker"** that attempted to access `apis.google.com` and `accounts.google.com`.
> 
> Since I had authorized saving my docs in Google Drive, I figured that the access was legit. So I just whitelisted the "tracker" (you can also just trust the entire site) in Ghostery.

That was the problem. As soon as I trusted StaskEdit at **Ghostery** the popup hasn't shown again.

Thanks @erhhung!
