### ISSUE TITLE
G-Suite: "Signed in as Unknown."

### ISSUE THREAD

**Issue by mforbes** [benweet/stackedit#1378]
When I sign in from my G-Suite for Education account, it lists me as "Signed in as **Unknown**."  Was hoping to use this for Team Drive collaboration but this means that comments etc. are not attributed to the users when they are signed in because they are all listed as by "Unknown".  (If I signin in with my regular personal gmail account works fine... it is something related to G-Suite logins.)

**Comment by mforbes** [comment]
I should add that I am able to sign in with my G-Suite account (and access files in my Team Drive) but comments etc. in StackEdit are attributed to "Uknown" and the message in the top right says "Signed in as **Unknown**."

**Comment by benweet** [comment]
Have you tried to update your Google Plus profile for the G-Suite account?

**Comment by mforbes** [comment]
No.  Google+ is not available for our organization.

**Comment by benweet** [comment]
Then StackEdit has no way to know about your identity I'm afraid.

**Comment by necopinus** [comment]
I don't think this is actually correct.

The organization I work for doesn't have Google+ active (I know this because I administer our G Suite instance, and I'm the one who turned that service off), but basic user information (first name, last name, and profile image) are still accessible via the OAuth2 API's https://www.googleapis.com/auth/plus.me scope (just checked this with a non-admin account in the [APIs Explorer](https://developers.google.com/apis-explorer/#p/oauth2/v2/oauth2.userinfo.get)).

(I know that the name _looks_ like it should be deactivated when you turn off the Google+ service, but it doesn't. And users can still non-centrally controlled information at https://aboutme.google.com/.)

**Comment by benweet** [comment]
@necopinus this would only allow StackEdit to have the name associated with your current account. Without Google Plus, your users won't be able to see who wrote comments for instance.
