### ISSUE TITLE
Some node shapes do not render in a Mermaid Flowchart diagram

### ISSUE THREAD

**Issue by bkulyk** [benweet/stackedit#1601]
Many node shapes do not render in a Mermaid Flowchart diagram

example:

> ```mermaid
> graph LR
> id1{{This is the text in the box}}
> database[(database)]
> hexagon{{This is the text in the box}}
> parallelogram[\This is the text in the box\]
> altParallelogram[/This is the text in the box/]
> trapezoid[/Christmas\]
> altTrapezoid[\Go shopping/]
> stadium([This is the text in the box])
> ```

I would expect to see 8 different shapes instead of a blank. This example does work in the mermaid live editor.

**Comment by smx-smx** [comment]
Have the same issue.
I have tried updating the mermaid library, but it's not as straightforward as i thought.

Installing the new version alone will not work, because `jison` files aren't pre-compiled by default anymore
Once i solved that problem (by compiling jison files manually), i got hit with an undefined reference error in `PrismJS`

**Comment by benweet** [comment]
Fixed with v5.14.10.
