### ISSUE TITLE
Self hosted StackEdit that operates on local files?

### ISSUE THREAD

**Issue by GregPK** [benweet/stackedit#192]
Would it be hard to setup StackEdit to work only on the files on the machine that it's been installed? 

The use case is that I have a private server to which I want to have access from various places, without the use it third party services like Google or Dropbox. 

So basically instead of choosing files to sync from external services, they would be chosen from the hard drive of the server.

PS. Great job on StackEdit!

**Comment by stefnotch** [comment]
@benweet How would one implement a custom synchronization provider? 
Is implementing [a custom provider](https://github.com/benweet/stackedit/tree/master/src/services/providers) and adding it to [syncSvc.js](https://github.com/benweet/stackedit/blob/master/src/services/syncSvc.js) enough? I assume that it's not, since [CouchDB's implementation is a lot bigger than that](https://github.com/benweet/stackedit/search?utf8=%E2%9C%93&q=couchdb&type=).

**Comment by gliviu** [comment]
The new Native File System proposal looks to be a good fit for this request.
Currently supported on Chrome, it allows transparent synchronization with local files.
Blog: https://web.dev/native-file-system/
Specs: https://wicg.github.io/native-file-system/
Sample: https://googlechromelabs.github.io/text-editor/

**Comment by schlichtanders** [comment]
> The new Native File System proposal looks to be a good fit for this request. Currently supported on Chrome, it allows transparent synchronization with local files. Blog: https://web.dev/native-file-system/ Specs: https://wicg.github.io/native-file-system/ Sample: https://googlechromelabs.github.io/text-editor/

That sounds like a perfect addition to StackEdit.
@gliviu would you mind opening a new more concrete issue which asks for support for such native file system in chrome?
