### ISSUE TITLE
Redundant Footnote

### ISSUE THREAD

**Issue by jmp0xf** [benweet/stackedit#274]
if an existing footnote is referred again, then a redundant footnote will be generated.
![qq20140120222238](https://f.cloud.github.com/assets/2247932/1954810/8df8e990-81de-11e3-8d25-9e7001ce8e60.png)

**Comment by mlopezgva** [comment]
Same here. Please, fix ASAP...

**Comment by shelby3** [comment]
Markdown on Gitlab doesn't have this flaw. Please fix this. This makes Stackedit entirely useless for whitepapers.

**Comment by shelby3** [comment]
@benweet wrote:
> I think it's the same behavior in MultiMarkdown and others flavored markdown syntaxes.

Are you stating basically that you are uninterested to fix this because you feel it is more compatible to have broken footnoting?

Why for two (and half) years has nothing been done to fix footnoting?

This project is a very useful product which _otherwise_ produces very beautifully (and quite complete feature set) rendered content. This footnote duplication issue is a giant wart (making it unusable) on an _otherwise_ awesome project.

**Comment by Jimsy2** [comment]
This bugs me, too. There are some Markdown renderers which handle duplicate footnotes more sophisticated. e.g.
https://markdown-it.github.io/
https://jbt.github.io/markdown-editor
http://dillinger.io

**Comment by benweet** [comment]
Using markdown-it for now.
