### ISSUE TITLE
RFE: Automatic synchronization of all documents with dropbox/drive

### ISSUE THREAD

**Issue by larsks** [benweet/stackedit#280]
I feel as if I have suggested this before, but I don't see an existing issue.  On the other hand, I am prone to forgetting things, which is really the motivation behind this RFE.

I would love to be able to point StackEdit at a DropBox (or Drive) folder and say, "hey, every document I create, sync it here".  I don't always remember to explicitly set up synchronization, which means that if I want to get at that document from my laptop that I started at my office...I'm out of luck.

With this sort of automatic synchronzation, I could sit down at any computer and (after initially connecting to dropbox or drive) and have access to all my documents, without needing to worry about explicit synchronization for each individual document.  Birds would sing and the sun would shine...

It would be awesome.

**Comment by MidnightLightning** [comment]
Trying to understand this limitation: When a user first presses "new document" in StackEdit, the document's title is "Title", so if it syncs right then, it would probably get the filename of "Title.md" or "Title.markdown" in Dropbox. You're saying that's bad because if a user changes the title of the document you can't change it in Dropbox?

Their v2 API endpoints do have a [move](https://www.dropbox.com/developers/documentation/http/documentation#files-move) endpoint (maybe that didn't exist two years ago?), so a document could retain its synchronization link after a move? It seems the ID numbers are now decorrelated, so maybe this case can be revisited?
