### ISSUE TITLE
Add GitLab Support

### ISSUE THREAD

**Issue by dklesev** [benweet/stackedit#303]
Please add GitLab Support if possible.
http://gitlab.org/
https://github.com/gitlabhq/gitlabhq

**Comment by killsudo** [comment]
Would love to see generic git publishing or at least gitlab support.

**Comment by sutch** [comment]
Another request for publishing to a git repository or integrating with Gitlab.

**Comment by cconover** [comment]
I'll throw in a vote for this as well.

**Comment by jampy** [comment]
+1

**Comment by o3o3o** [comment]
:+1

**Comment by o3o3o** [comment]
:+1:

**Comment by jampy** [comment]
Bounty available for this issue: https://www.bountysource.com/issues/1398663-add-gitlab-support !

**Comment by jampy** [comment]
Please allow also private GitLab installations, not just gitlab.com

**Comment by kingmaiku** [comment]
+1

**Comment by RafaelLeonhardt** [comment]
+1

**Comment by RafaelLeonhardt** [comment]
+1

**Comment by tarigancana** [comment]
+1

**Comment by vijaykrishnamurthy** [comment]
+1

**Comment by d3vr** [comment]
+1

**Comment by pierreozoux** [comment]
Any update on this? In it a big amount of work? Could we fund it on Bountysource?

**Comment by profedrini** [comment]
please?

**Comment by alerque** [comment]
@pierreozoux I've looked at doing this and it wouldn't be too hard in the sense that you don't need ninja programming skills, but it would take some time and effort. Basically somebody would need to  implement all the functions found in the [Github connector](https://github.com/benweet/stackedit/blob/master/public/libs/github.js) in such a way that it uses  the available Gitlab API functions. To my knowledge they are pretty similar, but not cross-compatible so each function would need to be researched, implemented, and tested.

**Comment by chaoflow** [comment]
I think so far gitlab support was discussed in the sense of publishing to github. For me it would be more interesting to have gitlab or a specific gitlab repository integrated like google drive to enable browsing of files and directories and automatically sync back to it.

**Comment by klevstul** [comment]
+1

**Comment by benweet** [comment]
Added GitLab workspaces, GitLab sync and GitLab publish in v5.13.

**Comment by GreenGremlin** [comment]
I see GitLab support was added to StackEdit! Is there documentation that details the extent of the integration?

**Comment by kahidna** [comment]
hi @benweet , glad to hear stackedit can integrated with gitlab. that's very cool.
I already integrated stackedit with my selfhost gitlab, and my question is : 
is it posible to edit file which part of git submodule using stackedit?

say I have project on gitlab named __sample1__. and then I add my other project as module say named __other2__ as a module. on other2__ project, I have file name __guide.md__.

I tried to edit using path __other2/guide.md__, but it's returned : __Could not open file other2/README.md.__

I need to do this because  I want to pool md files from each project into one project, so editing will use same path, e.g : _sample1/other2/guide.md_, _sample1/other3/guide.md_, _sample1/other4/guide.md_ and so on.

**Comment by josedacosta** [comment]
+1
