### ISSUE TITLE
updating existing blogger page

### ISSUE THREAD

**Issue by lustysoul** [benweet/stackedit#455]
I tested creating and updating blogger posts and pages, and it works well enough, but that was always with new nonsense documents I created for the purpose. When I had enough confidence to try and update an existing page, stackedit tells me that I don't have access to the google account. I never had any access issues when testing with new pages. I used the pageID that I copied from the page edit URL. I did that as well for the test pages I had created, so the access issue only occured once I was ready to test the sync with an existing page
I'm no programmer, so layman term please ;)

**Comment by flengyel** [comment]
I'm not able to get Blogger to recognize a PageId with StackEdit, whatever this is supposed to be. There is no clear definition of a PageId. Does it include the date portion of a URL? Does it only consist of thr appended number? There is no unambiguous statement. StackEdit fails silently when attempting to update an existing post or page, even if it was created with another instance of StackEdit. This limits the usefulness of StackEdit with blogger: pages and posts cannot be updated in another instance on another device, or with another instance in the same device. The only thing that works is creating a new page and deleting the old one from the new instance. What is StackEdit doing to keep track of the instances it can handle within the same instance, with the same cache?

**Comment by benweet** [comment]
@flengyel When you edit the post on blogger.com, you should have something like this in your address bar:
https://www.blogger.com/blogger.g?blogID=5845022475130620385#editor/target=post;postID=1032203568279282968;onPublishedMenu=posts;onClosedMenu=posts;postNum=3;src=postname

The postID is 1032203568279282968.
It should be the same with pageIDs.

**Comment by flengyel** [comment]
Thanks. Use of the PostID works in StackEdit with an already published post. In my case, I had to reconstruct the markdown from the post, since I did not seem to have the current version (or any version) cached in the browsers of the devices I had access to, and it had not yet been synchronized with Google Drive or Dropbox. It's a good idea to do this first (a prompt when a new document is created might help, or a one-time synchronization setting might be useful, as synchronization has to be done currently on a per-file basis, unless I am mistaken. I find that the PostID field is blank in StackEdit's publish and update dialog box after it is used. This must be cached also--perhaps it could be displayed with the post. Apologies for making suggestions without venturing into the code and submitting pull requests, since you generously make the code available.
