### ISSUE TITLE
 Error when trying to generate PDF: Bad Request

### ISSUE THREAD

**Issue by theoryshaw** [benweet/stackedit#671]
When exporting...

```
Error when trying to generate PDF: Bad Request
```
using Chrome Version 39.0.2171.99 m

same problem in....firefox 35.0

**Comment by benweet** [comment]
I can't reproduce this. Can you provide a markdown sample that provoke the issue?
Thx.

**Comment by theoryshaw** [comment]
https://raw.githubusercontent.com/OpeningDesign/Sports_Complex/1882483ef9cfe1aa4e30fd85bcd5fb6604fbe32d/Admin/Proposal/Proposal.MD

**Comment by benweet** [comment]
The image is not accessible for me (error 403) probably because it's on your own account and you must be logged in:
https://dl-web.dropbox.com/get/github/sports_complex/Models/xcel_logo.jpg?_subject_uid=7117445&w=AADqHbFWgdk2lJX-Sw6yisCu6DUsS1NLLy-6WjxHD9Fh3Q

If you remove it from the document it works fine.

**Comment by theoryshaw** [comment]
bingo, thanks.
