### ISSUE TITLE
This is not WYSIWYG

### ISSUE THREAD

**Issue by fulldecent** [benweet/stackedit#691]
This is not a WYSIWYG editor, recommending to remove that feature from the marketing material in README.md. The pinnacle feature, which stackedit does not have, is illustrated below:

![kismac2build](https://cloud.githubusercontent.com/assets/382183/6043558/fad32704-ac5a-11e4-98b1-90e62ef9e3dd.gif)

**Comment by davidsilvasmith** [comment]
What's the issue? That copy and paste doesn't retain formatting?

**Comment by fulldecent** [comment]
The issue is that WYSIWYG is advertised but it is not delivered.

A plain text editor with a browser next to it is not a WYSIWYG HTML editor. Likewise, this plain text editor with a renderer on the side is not a WYSIWYG Markdown editor.

This could be resolved by removing WYSIWYG from the feature list or by adding this actual capability to the program.

**Comment by mAAdhaTTah** [comment]
It doesn't say it's a WYSIWYG. From the README:

> WYSIWYG control buttons

i.e. Bold, italics buttons and such.

**Comment by davidsilvasmith** [comment]
I'm not the author, but it meets my definition of WYSIWYG. I make changes on the left they show on the right in real time. What I see is what I get.

That's why I don't understand the issue.

To meet your definition does it need to just have one view that is both the edit and live preview? Whereas the current implementation has separated the edit view from the live preview?

**Comment by fulldecent** [comment]
fair distinction, closing
