### ISSUE TITLE
Sharing link does not work if I have my own couchDB

### ISSUE THREAD

**Issue by patriklindstrom** [benweet/stackedit#707]
Eg this link does not work since it lacks my couchdb instance name that I have at smileupps.com
https://stackedit.io/editor#!provider=couchdb&id=nyzrisIARFQnMj9HrhVc0zbt
I think imho the sharing link should work if I have other then default db.
Its to complicated if I send a sharing link to a nontechnical person. I then have to include instructions for the to change default settings for couchdb.

**Comment by benweet** [comment]
It's not possible for a user to have multiple CouchDB configurations, that's why the CouchDB url is not included in the sharing link.
If you want your users to run on this CouchDB instance by default, I recommend you to install your own StackEdit server and change the default configuration in the code (then you probably want to fork the repo).

**Comment by askesian** [comment]
I'm trying to understand this. There is a warning when synchronizing with public couchdb, and it is suggested that I create my own. But once I create my own, I cannot use the share / collaboration feature, because that doesn't work with a custom couchdb instance. So, could you please clarify -- sharing / collaboration is completely off the table when using the public instance of stackedit and a custom couchdb instance?

**Comment by benweet** [comment]
The sharing links work out of the box with the default CouchDB instance. If you want collaborators to work on a custom instance (your own one) and share links of files that are saved in this instance, they would have to set the instance URL in the settings.
But then sharing links from the default instance won't work anymore... (does it really matter?)

**Comment by acusti** [comment]
I ran into this and noticed that the logic to download a file `onReady` [checks `getURLParameter`](https://github.com/benweet/stackedit/blob/master/public/res/sharing.js#L76) based on the value of [`downloadProvider.viewerSharingAttributes`](https://github.com/benweet/stackedit/blob/master/public/res/providers/downloadProvider.js#L12), which has only one attribute, `url`. However, that’s all that’s needed. If you take the sharing link generated by the sharing dialogue and append `&url=https://insertcustomcouchdburlhere.com/documents`, the link works.

So an easy fix would be to append that param to that url, which it seems could be accomplished by adding `"url"` to [`couchdbProvider.editorSharingAttributes`](https://github.com/benweet/stackedit/blob/master/public/res/providers/couchdbProvider.js#L25).

As for the use case, I think it makes sense to support this. If a team decides to use StackEdit and collaborate with it, they can set up a CouchDB instance that they share. Then, when they pass links around to each other, it will just work. Also, when someone, like myself, wants to share a file he’s working on with a non-StackEdit user, like his brother, to collaborate on it via StackEdit, it will work out of the box.

And as @askesian suggests, this seems like the kind of thing that a lot of people will run into.
