### ISSUE TITLE
Synchronising a folder on Dropbox / Google Drive

### ISSUE THREAD

**Issue by amitkot** [benweet/stackedit#748]
Currently synchronisation is only available on a file-by-file basis.
While it is possible to manually add multiple documents to the same folder on Dropbox or Google Drive, it isn't optimal as it takes extra time and is an error prone process - files may end up in a different Dropbox folder in case of typos.
It would be very useful if it was possible to synchronise a whole folder, and then any document that is in that folder would also get synchronised automatically.

**Comment by MidnightLightning** [comment]
Related: Issue #875 

When opening a file from Dropbox, in the file picker list, you can select multiple files at once, so you at least don't have to do that multiple times. But they're all imported into the root folder in StackEdit, so may need reorganization once there.

**Comment by jpaugh** [comment]
Another use case: I use both Chrome and Firefox at work and at home. I'd like to have the same folder structure synced to StackEdit (from Google Drive, in my case) in all of those instances. Otherwise, it doesn't make sense for me to use folders in StackEdit, since I'd have to redo that work 4 times.

Yet another use case: It would allow me to import all of my StackEdit4 documents into StackEdit5 in one fell swoop, rather than individually. Btw, Thanks @benweet for bringing us v5!

**Comment by benweet** [comment]
You can now use Google Drive workspaces in v5.
