### ISSUE TITLE
Published content quality

### ISSUE THREAD

**Issue by pulkitsinghal** [benweet/stackedit#814]
The published content on Google's blogger does not reflect what I see in the preview editor for Stackedit.

Can you provide some metrics on which published platforms reflect how much of Stackedit generated content faithfully? So users may make an educated switch.

Like:
Stackedit to Blogger (50%)
Stackedit to Wordpress (??%)
etc.

**Comment by SquidLord** [comment]
There is no way that that can actually be determined and used as a metric, since all the blog platforms are customizable to an extremely high degree through the use of site-specific CSS and other methods.

If that's your concern, your approaching StackEdit as an editor from the wrong direction.

StackEdit provides a means for editing content. That's all. The presentation is minimal because that is what is communicated by the markup itself, a minimal level of typographic control, with the actual presentation managed on the other side. There's no way that it has any way of knowing what "bold", for example, will actually mean on the other side – nor should it.
