### ISSUE TITLE
App freezes when bigger document is loaded.

### ISSUE THREAD

**Issue by Greg36** [benweet/stackedit#915]
When I open document with 20k words (with is not that much) the whole app freezes, CPU usage on that tab goes to ~25%. I waited like 2 minutes and It does not change.
I wanted to do a CPU usage profile but Chrome's DevTools freeze to, on that tab.

Dunno what causes that, like a month ago on the same PC I opened that document without any trouble.

**Comment by technobly** [comment]
I was trying to do the same thing recently either by opening the document or copy/pasting 130852 characters into a new document.  This caused the editor window to remain blank, and eventually crash the Chrome tab.  Now since doing this I can't open any of my documents (presumably because it's stuck trying to re-load that large file every time I open the editor).  

How do I reset the document it's trying to open to a different one?

**Comment by benweet** [comment]
Maybe try to use StackEdit recovery: https://stackedit.io/recovery.html

**Comment by technobly** [comment]
Thanks for the quick reply @benweet!  Unfortunately I already figured out how to reset it if the last document keeps crashing the app:

1. open https://stackedit.io, not the editor
2. right-click, select `inspect`
3. open Application tab
4. open stackedit.io local storage
5. find document text under Value
6. delete all keys associated with that document
7. the editor will now open

![screen_shot_2016-11-09_at_4_02_08_pm](https://cloud.githubusercontent.com/assets/2249224/20156720/24441066-a697-11e6-9863-cba1b8d2aeb7.png)

What exactly does the recover URL do?  I loaded it just to see and had a StackEdit local storage.json file download itself, and I don't see anything on the page.

**Comment by benweet** [comment]
You should have a way to remove files:

<img width="606" alt="screen shot 2016-11-09 at 22 17 33" src="https://cloud.githubusercontent.com/assets/1005257/20156939/6324c694-a6ca-11e6-8f0b-65777d7c7d62.png">

**Comment by technobly** [comment]
Oh I see now... it hadn't loaded initially, but now I see the instructions.  That's very slick!
![screen shot 2016-11-09 at 4 18 35 pm](https://cloud.githubusercontent.com/assets/2249224/20156973/41346382-a698-11e6-82c8-f80e67ba58b1.png)

I had to open and close the inspector to get it to load:
![screen shot 2016-11-09 at 4 19 32 pm](https://cloud.githubusercontent.com/assets/2249224/20156995/5f27a11a-a698-11e6-974f-f9433d44d951.png)

I wonder if there's a way to detect this large file issue and open the recovery URL instead of crashing :)  Would have saved me a lot of time.  Thanks for the great tool!

**Comment by benweet** [comment]
File contents are limited to 150KB in the v5.
