### ISSUE TITLE
Bug: won't render in Opera

### ISSUE THREAD

**Issue by Abbe98** [benweet/stackedit#925]
When using Opera 35 the following error is thrown and the application won't render:

```
Uncaught TypeError: RegExp.prototype.sticky getter called on non-RegExp object
main.js:4737
```

**Comment by CICCIOSGAMINO** [comment]
The same happen in Chrome version 48.0.2564.82 (Official Build) (64-bit) !! 

      Uncaught TypeError: RegExp.prototype.sticky getter called on non-RegExp object

**Comment by KrofDrakula** [comment]
Yup, had the same happen to me. I believe it's due to the minification tool, as the offending line is in the distributed [res-min/main.js](https://github.com/benweet/stackedit/blob/master/public/res-min/main.js) file:

```js
// line 4737
}, I = /\$(?:{([\w$]+)}|(\d\d?|[\s\S]))/g, D = x.exec.call(/()??/, "")[1] === e, N = RegExp.prototype.sticky !== e, M = {
```

The `sticky` prototype attribute cannot be called statically on the prototype, but must be called on an instance (like `N = /./s.sticky !== e`, which would fix the offending line). I guess Blink/Chromium changed that in recent versions which causes this to break.
