### ISSUE TITLE
Real time collaboration with multiple google accounts

### ISSUE THREAD

**Issue by Odepax** [benweet/stackedit#960]
This app should definitely allow real time editing and live chat like Google Docs.
I spoke about StackEdit to my colleagues and they were very disappointed about this fact.

For the rest, this app is amaze!

**Comment by selrond** [comment]
+1 This would be awesome indeed!

**Comment by Avinash-Bhat** [comment]
Actually, using the [Google Realtime API](https://developers.google.com/google-apps/realtime/collaborators), this might be possible.

Although going through other solutions, [HackMD](https://hackmd.io) has it covered. Although it doesn't share the functionality of sharing the file with others and linked documents with google drive (available in stackedit) -- document is saved to HackMD rather than to google drive. Also there is only exporting support due to the previous reason, which changes the document ID every time I export -- i.e., I have to share the newly exported file each time with the other person.

Maybe it's time that HackMD and stackedit combine (or at least steal from each other 😄)

PS: also it seems that both software generated files that are not compatible.

**Comment by benweet** [comment]
Realtime collaboration was available in the early versions. The feature was removed because hard to maintain. Sorry.
