### ISSUE TITLE
List formatting and preview weirdness

### ISSUE THREAD

**Issue by geckolinux** [benweet/stackedit#999]
Hi there, StackEdit is very nice. But there is a bit of weirdness with bulleted lists. I hope the following screenshots can illustrate the problem:

![screenshot from 2016-06-20 13-29-37](https://cloud.githubusercontent.com/assets/2692138/16205914/ab8ecd3e-36eb-11e6-97d5-02eccfaa7d29.png)
(Here it seems wrong that the "Level 1 bullet" text is bold in the editor pane, and also wrong that it is rendered as a heading in the preview.

![screenshot from 2016-06-20 13-29-55](https://cloud.githubusercontent.com/assets/2692138/16205929/bbff6552-36eb-11e6-954e-998bd0c9e665.png)
(Here it is also trying to interpret the next bullet at the same level as a heading.

![screenshot from 2016-06-20 13-30-14](https://cloud.githubusercontent.com/assets/2692138/16205976/ed3fce5e-36eb-11e6-8812-a8a3d310d335.png)
Here in the editor pane it automatically indents the next bullet, but once I type it moves it back to the correct level:

![screenshot from 2016-06-20 13-37-48](https://cloud.githubusercontent.com/assets/2692138/16206055/55e0578a-36ec-11e6-9a54-b0cba45c112b.png)

Thanks for taking a look!

**Comment by JacksonBailey** [comment]
About these points,

> Here it seems wrong that the "Level 1 bullet" text is bold in the editor pane, and also wrong that it is rendered as a heading in the preview.
> [...]
> Here it is also trying to interpret the next bullet at the same level as a heading.

I am guessing this is because it's easier to just look statically at what the content of the editor is rather than guessing what the user will type next.

To make the first two pictures display as having a new, empty list item then it'd have to guess you are about to type in the next list item as opposed to making the current list item a header. After that, there would need to be code to know when to stop assuming this and display what the content of the editor is supposed to actually display according to the spec.

So I wouldn't worry about those two points, but the last two seem more fishy.

**Comment by benweet** [comment]
Should be fixed in the v5.
